travis:
  secure:
    BINSTAR_TOKEN: i+nmkD42QkaUVdvuUCumBnkzhd6lad9zd2UBZIFLIduOt2eWyolwA+WjDFQ5+9eTg3llJV6QgqNG+xUMdu5OiHbLl14OgXgcDDfyL4fIGau4ywdhFob4Ft+XqDqw2eqOG8tqDZMgfshTGsjKbJWHbYVo0QG6+nJBgIePyxc6k1DBVGtL+Z8OM8K4IgCg0MLSoPuCYYv/5zs/tGYiMw8tW4P+iBNUN1X40vtoNIiPrF4lRRdwaXW9G7yflk4GWbNRRqCvxUm0hWoCzJcdGZw8CYZhWmzxP3tmU9vngnhMs8auTpGLFR+UCvJxbe7Gyn4e/ciBgInA9lRZCfdCiGEwoEiSGeMDHHldaGi71lO+oDeEuuYdVQR0XBlfzkaj+rwEfwgEup3eS/OBlet+d5CbZ+ML5u+MFAd7Zp5Q72LyPmXxjBJKfKH3Q4094Om/biZh/a3gFFibNH0JId1UJcJBCwOBQ9CF+MpadEnmSCaLLZYiMMiBztL4oLZIMNV1q25Efgezacl93SUDXTQCmWs7Zy8bLRHQ53M7qXCx1rQhNepFFWdfD4Q4zIj2zaOt9dOkctszPxilZ3DokpW1maW7g0NXRCyAQfYx2C6axJsu4L3lon96249g4VnZP+khNylTnOT4H/Pi1yEcX6vH909eBk0kTxnaekZs/wsHB5SZhgE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
